name: watchlist
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_bloc: ^8.0.0
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  core:
    path: ../core
  movies:
    path: ../movies
  tv_series:
    path: ../tv_series
  provider: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

